name: Approval Action

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: echo "Running unit tests..."

      - name: Run Linter
        run: echo "Linting the code..."

  deploy_to_testing:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: testing
    steps:
      - name: Deploy to Testing
        run: echo " Deploying to Testing environment..."

  deploy_to_staging:
    runs-on: ubuntu-latest
    needs: deploy_to_testing
    environment:
      name: staging

    steps:
      - name: Deploy to Staging
        run: echo " Deploying to Staging environment..."

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: deploy_to_staging
    environment:
      name: production
     
      deployment_protection_rules: []
    steps:
      - name: Deploy to Production
        run: echo "🚀 Deploying to Production environment..."
